services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    command: python run.py
    volumes:
      - ./backend:/app
      - ./data:/app/data
      - ./templates:/app/templates
    environment:
      - ENVIRONMENT=development

  worker:
    command: python -m app.workers.application_worker
    volumes:
      - ./backend:/app
      - ./data:/app/data
    environment:
      - ENVIRONMENT=development
