"""Extraction helpers for assistant-generated file artifacts."""

from __future__ import annotations

import re
from typing import Any

ARTIFACT_TAG_RE = re.compile(
    r"<artifact\s+([^>]*)>(.*?)</artifact>",
    re.IGNORECASE | re.DOTALL,
)
ATTR_RE = re.compile(r'([a-zA-Z_][\w-]*)\s*=\s*"([^"]*)"')
FENCED_BLOCK_RE = re.compile(
    r"```([a-zA-Z0-9_+.#-]*)[^\n]*\n(.*?)```",
    re.DOTALL,
)

MAX_ARTIFACTS = 6
FORMAT_ALIASES = {
    "md": "markdown",
    "markdown": "markdown",
    "text": "text",
    "txt": "text",
    "plain": "text",
    "py": "python",
    "js": "javascript",
    "ts": "typescript",
    "tsx": "tsx",
    "jsx": "jsx",
    "yml": "yaml",
}
FORMAT_EXTENSIONS = {
    "markdown": "md",
    "text": "txt",
    "python": "py",
    "javascript": "js",
    "typescript": "ts",
    "tsx": "tsx",
    "jsx": "jsx",
    "json": "json",
    "csv": "csv",
    "html": "html",
    "css": "css",
    "xml": "xml",
    "yaml": "yml",
    "sql": "sql",
    "bash": "sh",
    "shell": "sh",
    "dockerfile": "Dockerfile",
}
STRUCTURED_FORMATS = {"json", "csv", "html", "xml", "yaml", "toml", "ini", "sql"}
CODE_FORMATS = {
    "python",
    "javascript",
    "typescript",
    "tsx",
    "jsx",
    "java",
    "c",
    "cpp",
    "csharp",
    "go",
    "rust",
    "php",
    "ruby",
    "bash",
    "shell",
    "dockerfile",
    "css",
}


def extract_generated_artifacts(answer: str, query: str) -> tuple[str, list[dict[str, Any]]]:
    """Extract explicit and fenced artifacts while preserving display text."""
    tagged_artifacts, display_answer = _extract_tagged_artifacts(answer, query)
    fenced_artifacts = _extract_fenced_artifacts(display_answer, query, len(tagged_artifacts))
    artifacts = _dedupe_artifacts([*tagged_artifacts, *fenced_artifacts])

    if not artifacts:
        plain_artifact = _plain_file_artifact(display_answer, query)
        artifacts = [plain_artifact] if plain_artifact else []

    return _clean_display_answer(display_answer), artifacts[:MAX_ARTIFACTS]


def make_artifact(
    kind: str,
    title: str,
    content: str,
    *,
    file_format: str = "markdown",
    data: dict[str, Any] | None = None,
    description: str | None = None,
) -> dict[str, Any]:
    """Build the response shape expected by the chat API."""
    extension = FORMAT_EXTENSIONS.get(file_format, file_format)
    filename = f"{slug(title)}.{extension}"
    return {
        "type": kind,
        "title": title,
        "content": content,
        "format": file_format,
        "filename": filename,
        "description": description,
        "data": data or {},
    }


def title_from_query(query: str, file_format: str) -> str:
    text = re.sub(
        r"\b(make|build|create|generate|write|draft|regenerate|me|please|a|an|the|for|to|properly)\b",
        " ",
        query.lower(),
    )
    text = re.sub(r"[^a-z0-9+# ]+", " ", text)
    words = [word for word in text.split() if len(word) > 1][:6]
    base = " ".join(words) or "careerpilot artifact"
    if file_format not in base:
        base = f"{base} {file_format}"
    return _compact_title(base)


def looks_like_generation_request(query: str) -> bool:
    terms = ("draft", "write", "make", "build", "create", "generate", "regenerate")
    return any(term in query.lower() for term in terms)


def slug(text: str) -> str:
    value = re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")
    return value or "careerpilot-artifact"


def _extract_tagged_artifacts(answer: str, query: str) -> tuple[list[dict[str, Any]], str]:
    artifacts: list[dict[str, Any]] = []

    def replace(match: re.Match[str]) -> str:
        attrs = _parse_attrs(match.group(1))
        content = match.group(2).strip()
        if not content:
            return ""
        raw_format = attrs.get("type") or attrs.get("format") or "markdown"
        file_format = _normalize_format(raw_format)
        title = attrs.get("title") or _title_from_content(content) or title_from_query(query, file_format)
        artifact_id = slug(attrs.get("id") or title)
        artifacts.append(
            make_artifact(
                _artifact_kind(file_format, content),
                title,
                content,
                file_format=file_format,
                data={"artifact_id": artifact_id},
                description="Generated by Career Copilot.",
            )
        )
        return "\n"

    return artifacts, ARTIFACT_TAG_RE.sub(replace, answer)


def _extract_fenced_artifacts(
    answer: str,
    query: str,
    offset: int,
) -> list[dict[str, Any]]:
    artifacts: list[dict[str, Any]] = []
    for index, match in enumerate(FENCED_BLOCK_RE.finditer(answer), start=1):
        content = match.group(2).strip()
        file_format = _normalize_format(match.group(1) or _infer_format(content))
        if not _should_capture_fence(file_format, content):
            continue
        title = _title_from_content(content) or title_from_query(query, file_format)
        if index + offset > 1:
            title = f"{title} {index + offset}"
        artifacts.append(
            make_artifact(
                _artifact_kind(file_format, content),
                title,
                content,
                file_format=file_format,
                description="Extracted from a generated code or data block.",
            )
        )
    return artifacts


def _plain_file_artifact(answer: str, query: str) -> dict[str, Any] | None:
    content = answer.strip()
    if len(content) < 40:
        return None
    file_format = _infer_format(content)
    if file_format not in STRUCTURED_FORMATS:
        return None
    return make_artifact(
        _artifact_kind(file_format, content),
        title_from_query(query, file_format),
        content,
        file_format=file_format,
        description="Generated structured output.",
    )


def _parse_attrs(raw: str) -> dict[str, str]:
    return {key.lower(): value.strip() for key, value in ATTR_RE.findall(raw)}


def _normalize_format(raw: str) -> str:
    cleaned = raw.lower().strip().lstrip(".")
    return FORMAT_ALIASES.get(cleaned, cleaned or "markdown")


def _artifact_kind(file_format: str, content: str) -> str:
    if file_format in STRUCTURED_FORMATS:
        return f"{file_format}_file"
    if file_format in CODE_FORMATS:
        return "code_file"
    if file_format == "markdown" and _looks_like_rich_markdown(content):
        return "markdown_document"
    return "generated_file"


def _should_capture_fence(file_format: str, content: str) -> bool:
    if not content:
        return False
    if file_format in STRUCTURED_FORMATS:
        return len(content) >= 8
    if file_format in CODE_FORMATS:
        return len(content.splitlines()) >= 2 or len(content) >= 80
    if file_format == "markdown":
        return _looks_like_rich_markdown(content)
    return len(content) >= 220 and content.count("\n") >= 3


def _looks_like_rich_markdown(content: str) -> bool:
    lines = [line.strip() for line in content.splitlines() if line.strip()]
    heading_count = sum(line.startswith("#") for line in lines)
    list_count = sum(bool(re.match(r"^([-*]|\d+[.)])\s+", line)) for line in lines)
    return len(content) >= 300 or heading_count >= 2 or (heading_count >= 1 and list_count >= 4)


def _infer_format(content: str) -> str:
    stripped = content.strip()
    if (stripped.startswith("{") and stripped.endswith("}")) or (
        stripped.startswith("[") and stripped.endswith("]")
    ):
        return "json"
    if stripped.startswith("<!doctype html") or "<html" in stripped[:120].lower():
        return "html"
    first_line = stripped.splitlines()[0] if stripped else ""
    if re.search(r"^[-\w ]+(,[-\w ]+){1,}$", first_line):
        return "csv"
    if stripped.startswith("<?xml") or re.match(r"^<[\w:-]+[\s>]", stripped):
        return "xml"
    return "markdown"


def _title_from_content(content: str) -> str | None:
    for line in content.splitlines():
        cleaned = line.strip()
        if not cleaned:
            continue
        heading = re.match(r"^#{1,3}\s+(.+)$", cleaned)
        if heading:
            return _compact_title(heading.group(1))
        filename = re.match(r"^(?:#|//|--)\s*(?:file|filename):\s*(.+)$", cleaned, re.I)
        if filename:
            return _compact_title(filename.group(1))
    return None


def _compact_title(text: str) -> str:
    words = re.sub(r"[_-]+", " ", text).strip().split()
    title = " ".join(words[:8]).strip(" .:")
    return title[:1].upper() + title[1:] if title else "Generated artifact"


def _clean_display_answer(answer: str) -> str:
    return re.sub(r"\n{3,}", "\n\n", answer).strip()


def _dedupe_artifacts(artifacts: list[dict[str, Any]]) -> list[dict[str, Any]]:
    unique: list[dict[str, Any]] = []
    seen: set[tuple[str, str]] = set()
    for artifact in artifacts:
        key = (str(artifact.get("format", "")), str(artifact.get("content", "")).strip())
        if key in seen:
            continue
        seen.add(key)
        unique.append(artifact)
    return unique
