import { useState } from 'react';
import Box from '@mui/material/Box';
import Button from '@mui/material/Button';
import Card from '@mui/material/Card';
import CardContent from '@mui/material/CardContent';
import Chip from '@mui/material/Chip';
import Dialog from '@mui/material/Dialog';
import DialogActions from '@mui/material/DialogActions';
import DialogContent from '@mui/material/DialogContent';
import DialogTitle from '@mui/material/DialogTitle';
import Grid from '@mui/material/Grid';
import Stack from '@mui/material/Stack';
import TextField from '@mui/material/TextField';
import Typography from '@mui/material/Typography';
import ContentCopyIcon from '@mui/icons-material/ContentCopy';
import DeleteIcon from '@mui/icons-material/Delete';
import DownloadIcon from '@mui/icons-material/Download';
import EditIcon from '@mui/icons-material/Edit';
import Inventory2Icon from '@mui/icons-material/Inventory2';

import { ArtifactVisualizer } from '@/components/assistant/ArtifactVisualizer';
import ErrorBoundary from '@/components/common/ErrorBoundary';
import { useArtifactStore, type StoredArtifact } from '@/store/useArtifactStore';
import { artifactFormat, downloadArtifact } from '@/utils/artifactFiles';

function ArtifactsPage() {
  const artifacts = useArtifactStore((s) => s.artifacts);
  const updateArtifact = useArtifactStore((s) => s.updateArtifact);
  const removeArtifact = useArtifactStore((s) => s.removeArtifact);
  const clearArtifacts = useArtifactStore((s) => s.clearArtifacts);
  const [editing, setEditing] = useState<StoredArtifact | null>(null);
  const [draft, setDraft] = useState('');

  const copyArtifact = async (content: string) => {
    await navigator.clipboard.writeText(content);
  };

  const editArtifact = (artifact: StoredArtifact) => {
    setEditing(artifact);
    setDraft(artifact.content);
  };

  const saveArtifact = () => {
    if (!editing) return;
    updateArtifact(editing.id, draft);
    setEditing(null);
  };

  return (
    <ErrorBoundary>
      <Box>
        <Stack direction={{ xs: 'column', md: 'row' }} spacing={2} justifyContent="space-between" sx={{ mb: 3 }}>
          <Box>
            <Typography variant="h4" gutterBottom>
              Assistant Artifacts
            </Typography>
            <Typography variant="body1" color="text.secondary">
              Reuse cover letters, readiness reports, gap analyses, and roadmaps generated by Copilot.
            </Typography>
          </Box>
          <Button color="error" startIcon={<DeleteIcon />} onClick={clearArtifacts} disabled={artifacts.length === 0}>
            Clear all
          </Button>
        </Stack>

        {artifacts.length === 0 ? (
          <Box sx={{ textAlign: 'center', py: 8 }}>
            <Inventory2Icon sx={{ fontSize: 64, color: 'text.disabled', mb: 2 }} />
            <Typography variant="h6" color="text.secondary">
              No artifacts yet
            </Typography>
            <Typography variant="body2" color="text.secondary">
              Ask Copilot for a roadmap, cover letter, skill gap report, or readiness verdict.
            </Typography>
          </Box>
        ) : (
          <Grid container spacing={2}>
            {artifacts.map((artifact) => (
              <Grid item xs={12} md={6} key={artifact.id}>
                <Card>
                  <CardContent>
                    <Stack direction="row" spacing={1} alignItems="center" sx={{ mb: 1 }}>
                      <Typography variant="h6" sx={{ flex: 1 }}>
                        {artifact.title}
                      </Typography>
                      <Chip size="small" label={artifact.type.replace(/_/g, ' ')} />
                      <Chip size="small" variant="outlined" label={artifactFormat(artifact)} />
                    </Stack>
                    <Typography variant="caption" color="text.secondary">
                      {new Date(artifact.created_at).toLocaleString()}
                    </Typography>
                    {artifact.description && (
                      <Typography variant="body2" color="text.secondary" sx={{ mt: 1 }}>
                        {artifact.description}
                      </Typography>
                    )}
                    <ArtifactVisualizer artifact={artifact} />
                    <Typography sx={{ mt: 2, whiteSpace: 'pre-line' }} variant="body2">
                      {artifact.content}
                    </Typography>
                    <Stack direction="row" spacing={1} sx={{ mt: 2 }}>
                      <Button size="small" startIcon={<ContentCopyIcon />} onClick={() => copyArtifact(artifact.content)}>
                        Copy
                      </Button>
                      <Button size="small" startIcon={<EditIcon />} onClick={() => editArtifact(artifact)}>
                        Edit
                      </Button>
                      <Button size="small" startIcon={<DownloadIcon />} onClick={() => downloadArtifact(artifact)}>
                        Download
                      </Button>
                      <Button
                        size="small"
                        color="error"
                        startIcon={<DeleteIcon />}
                        onClick={() => removeArtifact(artifact.id)}
                      >
                        Delete
                      </Button>
                    </Stack>
                  </CardContent>
                </Card>
              </Grid>
            ))}
          </Grid>
        )}
        <Dialog open={Boolean(editing)} onClose={() => setEditing(null)} fullWidth maxWidth="md">
          <DialogTitle>Edit Artifact</DialogTitle>
          <DialogContent>
            <TextField
              fullWidth
              multiline
              minRows={12}
              value={draft}
              onChange={(event) => setDraft(event.target.value)}
              sx={{ mt: 1 }}
            />
          </DialogContent>
          <DialogActions>
            <Button onClick={() => setEditing(null)}>Cancel</Button>
            <Button variant="contained" onClick={saveArtifact}>
              Save
            </Button>
          </DialogActions>
        </Dialog>
      </Box>
    </ErrorBoundary>
  );
}

export default ArtifactsPage;
